# Invoice Template Configuration

# Path to the template PDF file
template_path = "template.pdf"

# Field recognition settings
[field_recognition]
confidence_threshold = 0.85
use_fuzzy_matching = true
allow_multiple_matches = false
threshold_for_fuzzy_match = 90  # Percentage of similarity required for fuzzy matching

# Define the fields to recognize with their expected coordinates and types
[[fields]]
name = "invoice_number"
type = "text"
region = [0.7, 0.1, 0.9, 0.15]
description = "Unique invoice identifier"

[[fields]]
name = "date"
type = "date"
region = [0.7, 0.15, 0.9, 0.2]
description = "Invoice issue date"

[[fields]]
name = "customer_name"
type = "text"
region = [0.1, 0.2, 0.5, 0.25]
description = "Name of the customer"

[[fields]]
name = "customer_id"
type = "text"
region = [0.1, 0.38, 0.3, 0.43]
description = "Customer ID code"

[[fields]]
name = "po_number"
type = "text"
region = [0.3, 0.38, 0.5, 0.43]
description = "Purchase order number"

[[fields]]
name = "service_period"
type = "text"
region = [0.5, 0.38, 0.7, 0.43]
description = "Service period"

[[fields]]
name = "terms"
type = "text"
region = [0.7, 0.38, 0.9, 0.43]
description = "Payment terms"

[[fields]]
name = "total_amount"
type = "amount"
region = [0.7, 0.8, 0.9, 0.85]
description = "Total invoice amount"

# Table extraction configuration
[table_extraction]
table_region = [0.05, 0.43, 0.95, 0.75]
header_row = true
column_mapping = [
    {name = "site_name", index = 0},
    {name = "item", index = 1},
    {name = "quantity", index = 2},
    {name = "rate", index = 3},
    {name = "description", index = 4},
    {name = "subtotal", index = 5},
    {name = "tax_rate", index = 6}
]
